name: 'Emoji Linter'
description: 'Detect and remove emojis from your code. Keep your codebase clean and professional.'
author: 'Emily Cogsdill'

branding:
  icon: 'eye'
  color: 'yellow'

inputs:
  path:
    description: 'Path to scan for emojis (relative to repository root)'
    required: false
    default: '.'
  mode:
    description: 'Operation mode: "check" (error if emojis found) or "fix" (remove emojis)'
    required: false
    default: 'check'
  github-token:
    description: 'GitHub token for authentication (use default GITHUB_TOKEN)'
    required: false

outputs:
  has-emojis:
    description: 'Whether any emojis were found (true/false)'
  emoji-count:
    description: 'Total number of emojis found'
  files-with-emojis:
    description: 'Number of files containing emojis'

runs:
  using: 'node20'
  main: 'dist/index.js'