name: 'Emoji Linter'
description: 'GitHub Action to validate emoji usage in commits, PRs, and branches with configurable modes'
author: 'Emily Cogsdill'

branding:
  icon: 'eye'
  color: 'yellow'

inputs:
  path:
    description: 'Path to scan for emojis (relative to repository root)'
    required: false
    default: '.'
  mode:
    description: 'Validation mode: "clean" (detect emojis for cleanup), "forbid" (ensure no emojis exist)'
    required: false
    default: 'clean'
  config-file:
    description: 'Path to emoji-linter configuration file'
    required: false
    default: '.emoji-linter.config.json'
  comment-pr:
    description: 'Whether to post a comment on pull requests with results'
    required: false
    default: 'false'
  fail-on-error:
    description: 'Whether to fail the action when emojis violate the specified mode rules'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token for posting PR comments (automatically provided in most cases)'
    required: false
    default: ${{ github.token }}

outputs:
  has-emojis:
    description: 'Whether any emojis were found (true/false)'
  emoji-count:
    description: 'Total number of emojis found across all files'
  files-with-emojis:
    description: 'Number of files containing emojis'
  total-files:
    description: 'Total number of files scanned'
  results:
    description: 'Detailed results in JSON format'

runs:
  using: 'node20'
  main: 'dist/index.js'